
language: r
cache: packages

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libssl-dev
      - libxml2-dev

before_install:
  - R -e 'install.packages("remotes")'

install:
  - R -e 'remotes::install_cran("bookdown")'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _book
  github_token: $GITHUB_TOKEN  # Set this in Travis repo settings
  keep_history: true
  on:
    branch: master
