# Table of Contents

- [Foreword](index.html#foreword)
  - [Acknowledgements](index.html#acknowledgements)
- [Table of Contents](00-toc.html#table-of-contents)
- [Introduction](01-introduction.html#introduction)
  - [The Problem Domain and Approach](01-introduction.html#the-problem-domain-and-approach)
  - [Motivations](01-introduction.html#motivations)
    - [Generalising beyond jazz](01-introduction.html#generalising-beyond-jazz)
  - [Thesis Statement](01-introduction.html#thesis-statement)
  - [Original Contributions](01-introduction.html#original-contributions)
  - [Research Questions](01-introduction.html#research-questions)
  - [Objectives and Scope](01-introduction.html#objectives-and-scope)
    - [Scope](01-introduction.html#scope)
  - [Front-Facing Tools](01-introduction.html#front-facing-tools)
    - [Slonimsky.app](01-introduction.html#slonimskyapp)
    - [Songbird.training](01-introduction.html#songbirdtraining)
  - [Dissertation Outline](01-introduction.html#dissertation-outline)
- [Foundations](02-foundations.html#foundations)
  - [What is playing by ear?](02-foundations.html#what-is-playing-by-ear)
  - [Learning to play by ear](02-foundations.html#learning-to-play-by-ear)
- [Historical Background: Approaches to Improving Playing by Ear in Jazz Pedagogy](03-historical_background.html#historical_background)
  - [The Aural Origins of Jazz Education](03-historical_background.html#the-aural-origins-of-jazz-education)
  - [Record Players as Pedagogical Tools](03-historical_background.html#record-players-as-pedagogical-tools)
  - [Codification of Jazz Education](03-historical_background.html#codification-of-jazz-education)
  - [The Chord-Scale Approach, Pattern Books and Vocabulary Acquisition](03-historical_background.html#the-chord-scale-approach-pattern-books-and-vocabulary-acquisition)
  - [The Influence of John Coltrane](03-historical_background.html#the-influence-of-john-coltrane)
  - [Slonimsky's Thesaurus and Jazz Improvisation](03-historical_background.html#slonimskys-thesaurus-and-jazz-improvisation)
  - [Modern Technological Approaches to Ear Training](03-historical_background.html#modern-technological-approaches-to-ear-training)
  - [Integration of Technology in Educational Settings](03-historical_background.html#integration-of-technology-in-educational-settings)
  - [Conclusion](03-historical_background.html#conclusion)
- [Empirical Backgrounds: Systematic Musicological and Cognitive Psychological](04-empirical_backgrounds.html#empirical_backgrounds)
  - [Music and combinatorics](04-empirical_backgrounds.html#music-and-combinatorics)
- [library(musiccombinatoricsr)](04-empirical_backgrounds.html#librarymusiccombinatoricsr)
  - [Melody as Cognitive Psychology / Melodic represention](04-empirical_backgrounds.html#melody-as-cognitive-psychology-melodic-represention)
  - [Computed melodic features as a solution to selecting items](04-empirical_backgrounds.html#computed-melodic-features-as-a-solution-to-selecting-items)
  - [Pattern books as item banks](04-empirical_backgrounds.html#pattern-books-as-item-banks)
- [Playing By Ear: A Theoretical Model](05-playing-by-ear-a-theoretical-model.html#theoretical-model)
  - [Pfordresher's H-PAC model](05-playing-by-ear-a-theoretical-model.html#pfordreshers-h-pac-model)
  - [Pfordresher's cognitive model of singing accuracy](05-playing-by-ear-a-theoretical-model.html#pfordreshers-cognitive-model-of-singing-accuracy)
  - [Baker's computational model of melodic dictation](05-playing-by-ear-a-theoretical-model.html#bakers-computational-model-of-melodic-dictation)
  - [Models of sung recall](05-playing-by-ear-a-theoretical-model.html#models-of-sung-recall)
  - [Non-musical models of serial recall](05-playing-by-ear-a-theoretical-model.html#non-musical-models-of-serial-recall)
  - [WM bits](05-playing-by-ear-a-theoretical-model.html#wm-bits)
  - [Bringing it together](05-playing-by-ear-a-theoretical-model.html#bringing-it-together)
  - [Moving from Theoretical to Computational](05-playing-by-ear-a-theoretical-model.html#moving-from-theoretical-to-computational)
    - [Inputs](05-playing-by-ear-a-theoretical-model.html#inputs)
    - [Sequential Construction](05-playing-by-ear-a-theoretical-model.html#sequential-construction)
    - [Function Application](05-playing-by-ear-a-theoretical-model.html#function-application)
  - [Mathematical Representation](05-playing-by-ear-a-theoretical-model.html#mathematical-representation)
  - [Algorithm Flow](05-playing-by-ear-a-theoretical-model.html#algorithm-flow)
  - [Final Equation](05-playing-by-ear-a-theoretical-model.html#final-equation)
  - [Strategies](05-playing-by-ear-a-theoretical-model.html#strategies)
  - [Learning, forgetting](05-playing-by-ear-a-theoretical-model.html#learning-forgetting)
  - [The Melodic Mind As Item Bank](05-playing-by-ear-a-theoretical-model.html#the-melodic-mind-as-item-bank)
  - [Predictions:](05-playing-by-ear-a-theoretical-model.html#predictions)
- [A computational ecosystem](06-computational-ecosystem.html#computational-ecosystem)
  - [pyin:](06-computational-ecosystem.html#pyin)
  - [Psychologically meaningful musical item banks: itembankr](06-computational-ecosystem.html#psychologically-meaningful-musical-item-banks-itembankr)
  - [Datasets](06-computational-ecosystem.html#datasets)
    - [WJD](06-computational-ecosystem.html#wjd)
    - [Berkowitz](06-computational-ecosystem.html#berkowitz)
    - [Slonimsky](06-computational-ecosystem.html#slonimsky)
  - [Other useful functions](06-computational-ecosystem.html#other-useful-functions)
    - [Assessing musical behaviours: musicassessr](06-computational-ecosystem.html#assessing-musical-behaviours-musicassessr)
  - [Ability tests](06-computational-ecosystem.html#ability-tests)
  - [Conclusion](06-computational-ecosystem.html#conclusion)
- [Experiment 1: Development of a melodic similarity algorithm for short recalled melodies](07-development-of-melodic-similarity-algorithm-for-short-melodies.html#melsim_development)
- [Experiment 2: An Explanatory Model Of Playing By Ear](08-main_pbe_study_lab.html#pbet_lab_study)
  - [Visual vs. Auditory Learning](08-main_pbe_study_lab.html#visual-vs-auditory-learning)
- [Modelling Melodic Difficulty in Playing by Ear: An Item Response Analysis of Online Performance Data](09-main_pbe_study_online.html#pbet_online_study)
- [Experiment 3: A Longitudinal Study of Playing By Ear Skills](10_study_history_study.html#study_history_study)
  - [Production perception paradigm](10_study_history_study.html#production-perception-paradigm)
- [Experiment 4: A similarity-based approach to item selection](11-similarity_modelling_study.html#similarity_study)
  - [Melodic corpora as networks](11-similarity_modelling_study.html#melodic-corpora-as-networks)
  - [Approaches to similarity for large scale corpora](11-similarity_modelling_study.html#item_banks_and_similarity)
    - [Problem:](11-similarity_modelling_study.html#problem)
- [WJD_no_items <- nrow(WJD::WJD('phrases'))](11-similarity_modelling_study.html#wjdnoitems---nrowwjdwjdphrases)
- [factorial(WJD_no_items)](11-similarity_modelling_study.html#factorialwjdnoitems)
    - [Approach #1: similarity of features as proxy for melodic similarity](11-similarity_modelling_study.html#approach-1-similarity-of-features-as-proxy-for-melodic-similarity)
    - [Approach #2: Generative similarity](11-similarity_modelling_study.html#approach-2-generative-similarity)
    - [Approach #3: on breaking up items into ngrams, store representations/similarity.](11-similarity_modelling_study.html#approach-3-on-breaking-up-items-into-ngrams-store-representationssimilarity)
- [Experiment 5: Model synthesis: Development of a musical DASH+SIM model](12-DASH_model.html#experiment-5-model-synthesis-development-of-a-musical-dashsim-model)
- [Additional Learning Paradigms](13-learning_paradigms.html#additional-learning-paradigms)
  - [Generative similarity](13-learning_paradigms.html#generative-similarity)
  - [identify correct vs incorrect ngrams in a recall: add incorrect ngrams to beginning of session buffer](13-learning_paradigms.html#identify-correct-vs-incorrect-ngrams-in-a-recall-add-incorrect-ngrams-to-beginning-of-session-buffer)
- [Experiment 6: An Interventional Study](14-an_interventional_study.html#interventional_Study)
