
# Empirical Backgrounds: Systematic Musicological and Cognitive Psychological {#empirical_backgrounds}


Having motivated this work in terms of historical context, I will now turn to motivating it in terms of the epistemological approaches taken to assess this question. These approaches are: systematic musicological, psychological, and computational. In general, these approaches come from the *scientific approach*. 

The derivation of Slonimsky's *Thesaurus* - a new to document and rationalise logical melodic vocabulary - leads to a more general issue around combinatorics and musical (melodic) material.


## Music and combinatorics

- Introduce notion of large melodic learning vocabularies (LMLVs), ?

```{r}
# library(musiccombinatoricsr)

```


## Melody as Cognitive Psychology / Melodic represention


[@herbornFeaturesPerceptionConstruction2022]

## Computed melodic features as a solution to selecting items



## Pattern books as item banks

The book has at least 1,400 discrete items and some of the patterns are terrifically long and complicated. Additionally, nearly all of the melodies are presented from a single note, C, and could be transposed to start on the other 11 chromatic tones. This means there are at least 16,800 (12 * 1400) items to be learned. The author’s saxophone tutor, who was a virtuoso, once said, "Oh, don't bother trying to learn [Slonimsky’s Thesaurus of Scales and Melodic Patterns] systematically". This was a wise comment since, as there is so much information, it is almost impossible for a human to comprehend and track their learning of it systematically. However, with advances in computation, this is a relatively easy challenge to solve once the data is in digital form. The author entered the Slonimsky’s Thesaurus corpus into his computer to provide a digital representation. This corpus will remain the test case for description in this document later on.