
---
title: "Playing By Ear: A Computational Approach"
author: "Seb Silas"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook: default
bibliography: references.bib
documentclass: book
---


# Front Matter

> "I love science, and it pains me to think that so many are terrified of the subject or feel that choosing science means you cannot also choose compassion, or the arts, or be awed by nature. Science is not meant to cure us of mystery, but to reinvent and reinvigorate it."  
> — *Robert Sapolsky* [@sapolskyWhyZebrasDont2004]


## Foreword


The topic of this dissertation is "playing by ear" and whilst I generalise the results, I motivate this mainly in terms of jazz education.


Jazz is an oral tradition.


Cognitive psychological tool

If you want to learn the tradition, transcribe the solos, go and play with new solos.

Less a means of learning the tradition orally (best go straight to the source, transcribe real solos) - more about developing personal vocabulary based on your current knowledge. Exploring new spaces


The computer as the "heavy-lifter" so the musician can focus more on the sounds themselves; unburdening the musician



## Acknowledgements


For Soraya.


Sylvia,


Daniel Müllensiefen, Reinhard Kopiez.

Klaus Frieler, 

Mohamed Etteyeb

Peter Harrison, Kilian Sander, 

Antoine Sachet, James Petticrew, 

Annabel Cohen


<!-- for graphics -->

<!--

<a href="https://www.flaticon.com/free-icons/saxophone" title="saxophone icons">Saxophone icons created by Nsit - Flaticon</a>

-->

## Table of Contents {#toc}

```{r child="_includes/_toc_content.Rmd"}


```

